### PR TITLE
Html snippets

### PR DESCRIPTION
**Pull request by Leeds-eBooks**
As discussed in [this forum thread](https://forums.appgyver.com/#!/steroids:is-there-a-better-way-to-ma), new functionality to support html 'snippets'.

To use the new functionality, create a new snippets folder in `app/common`, and put your snippet html files in there. Inject any of your snippets by using `<%= yield.snippets['your-snippet-filename'] %>` (don't include ‘.html’ in the filename here!).

It also works with putting snippets in any of your module folders (under a `snippets` directory there). What I don't think will work is putting snippets inside snippets, i.e. nesting.

### CODE REVIEW

**Comment by harsaharsa** [comment]
Thanks for this! I'll try to review it ASAP and get it merged, looks like a useful addition.

**Comment by Leeds-eBooks** [comment]
Great! If you think it could be improved just let me know.

**Comment by Leeds-eBooks** [comment]
Sorry to bump but been using this for a while now and no problems so far. Any chance of getting this merged?

**Comment by harsaharsa** [comment]
The plan is that @Sampax will take a look at this and merge next week. Sorry for the delay!

**Comment by Leeds-eBooks** [comment]
@harsaharsa Ok that's fine, no need to apologize!

I've also modified my fork to run js files through Babel if the following command is run:
```
$ steroids connect --gruntTask=babel
```
Are you guys already working on babel/es6 support? If not, is it worth submitting a PR? I haven't done it very elegantly (just copied the whole `tasks/fresh` folder to `tasks/babel` and changed the necessary subtasks) but it works.

**Pull request closed without merging**
